"""empty message

Revision ID: d0e7d5802dfe
Revises: 3a9f32ccee69
Create Date: 2023-07-16 20:04:02.639226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0e7d5802dfe'
down_revision = '3a9f32ccee69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catagories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catagories', schema=None) as batch_op:
        batch_op.drop_column('img')

    # ### end Alembic commands ###